apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-demo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/FaresMirza/test-vault
    targetRevision: main
    path: .
    helm:
      # Enable helm-secrets to decrypt SOPS files
      valueFiles:
        - secrets://secrets.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
