apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
      - name: ngrok
        image: ngrok/ngrok:latest
        args:
          - "http"
          - "vault:8200"
        env:
        - name: NGROK_AUTHTOKEN
          valueFrom:
            secretKeyRef:
              name: ngrok-auth
              key: NGROK_AUTHTOKEN
        ports:
        - containerPort: 4040
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: ngrok
  namespace: vault
spec:
  selector:
    app: ngrok
  ports:
  - port: 4040
    targetPort: 4040
    name: web
